# Jekyll Resume Theme

# Site settings
title: Pankesh Bamotra
email: pankesh.bamotra@gmail.com
description: Resume, projects, and brief about Pankesh Bamotra.
baseurl: ""
url: "https://pnksh.me/"
name: Pankesh Bamotra
job: data scientist
location: Seattle, Washington
languages: Python, machine learning, and statistics
twitter_username: _pbamotra_
github_username:  pbamotra
email_address: pankesh.bamotra@gmail.com
blog: https://basicml.com/
counsel: https://cmu.firsthand.co/profile/7860547#!

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap